runtime: nodejs16
handlers:
  # Serve all static files urls ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
  # Catch all handlers to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html